//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.08 at 04:19:07 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.afroprogrammer.com/spring/boot/soap/api/loanEligibility", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.afroprogrammer.spring.soap.ws.client.loaneligibility;
